Accept credentials as impl Read
ywegel/oauth_fcm pull request #9
Opened 2024-06-20 19:07 UTC by aengelas

Currently, the credentials are expected to be passed as a path to a file on disk, but as type &str. These changes update the interface to accept anything that impl Read, which means you can pass a file handle, &[u8], buffers, etc.

This constitutes a breaking change in the interface; the burden is put on the caller to open the file, read the file, get the credentials from the environment, etc. However, the advantage is that the interface is more flexible.

I also updated all the existing tests to succeed, and added a test verifying that it also succeeds when passing the credentials as a byte slice.

If the breaking change is a problem, we could also leave the impl Read interface on the TokenManager itself, but provide an additional top-level function called something like
create_shared_token_manager_from_slice, or ..._from_reader, etc. I personally prefer the cleaner single flexible entrypoint, but it's not my project!

2024-06-20 19:22 UTC, ywegel commented
This looks pretty good, thank you! I will try to take a look at this this or next weekend

2024-06-21 16:11 UTC, aengelas commented
Cool! Hope it's helpful.

2024-06-21 16:44 UTC, aengelas commented
I just pushed changes to (hopefully) fix the failing rustfmt check.

2024-06-22 07:42 UTC, ywegel commented
To fix the rustfmt check you dont need the rustfmt.toml. just run the rustfmt command in your terminal before pushing it to the repo. Then everything is formatted correctly

2024-06-22 12:15 UTC, ywegel commented
It looks good to me. If you remove the rustfmt.toml and format your code, I can merge it. Also FYI, I added a CONSTRIBUTION.md file. By contributing to this project, you agree that your contributions will be licensed under the same license as the project (see LICENSE file)

2024-06-22 13:44 UTC, ywegel requested changes
Please add a line similar to this to the "unreleased" section of the Changelog.md:
`- Accept FCM credentials as impl Read (#9)`

2024-06-25 16:06 UTC, aengelas commented
> To fix the rustfmt check you dont need the rustfmt.toml. just run the rustfmt command in your terminal before pushing it to the repo. Then everything is formatted correctly

The problem with that is that I have workstation rustfmt settings in ~/.config/rustfmt/rustfmt.toml that are used by default if there's no rustfmt.toml in a given repo. So if I just run cargo fmt it will reformat files to match my settings. Not a huge deal, but either way I'll need that empty file at least temporarily in order to apply the formatting.

2024-06-25 16:45 UTC, aengelas commented
> I just pushed changes to (hopefully) fix the failing rustfmt check.

I guess it prob wasn't clear; the changes I'm talking about here were to my actual contributions. I _also_ added that rustfmt.toml just so I could consistently run rustfmt. At any rate, I've pulled the rustfmt commit out.

2024-06-27 11:42 UTC, ywegel approved these changes

2024-06-27 11:44 UTC, merged

2024-06-27 11:45 UTC, ywegel commented
Thank you for contributing :)

2024-06-27 12:54 UTC, ywegel commented
Closes #12